[tool.poetry]
name = "test-gather-plan"
version = "0.1.0"
description = ""
authors = ["socar-piglet <socar-piglet@socar.kr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
reflex = "^0.4.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
